import { glob } from "tinyglobby";
import fs from "node:fs/promises";
import path from "node:path";

/**
 * @typedef {Object} Options
 * @property {string} [routesDir='src/routes'] - Where your SvelteKit routes live.
 * @property {string} [outputFile='src/lib/generated/routes.ts'] - Where to write the helper.
 */

/**
 * @param {Options} options
 * @returns {import('vite').Plugin}
 */
export function svelteNamedRoutes(options = {}) {
  const {
    routesDir = "src/routes",
    outputFile = "src/lib/generated/routes.ts",
  } = options;

  const sync = async () => {
    const files = await glob(`${routesDir}/**/+page.{ts,js,svelte}`);
    const map = {};

    for (const file of files) {
      const content = await fs.readFile(file, "utf-8");
      const match = content.match(/name:\s*['"](.+?)['"]/);

      if (match) {
        const name = match[1];
        let routePath = file
          .replace(routesDir, "")
          .split("/")
          .filter((segment) => !segment.startsWith("+"))
          .filter(
            (segment) => !segment.startsWith("(") || !segment.endsWith(")"),
          )
          .join("/");

        routePath = "/" + routePath.replace(/\/$/, "").replace(/^\/+/, "");
        map[name] = routePath;
      }
    }

    const content = `
// THIS FILE IS AUTO-GENERATED BY SVELTE-NAMED-ROUTES. DO NOT EDIT.
export const routes = ${JSON.stringify(map, null, 2)} as const;

export type RouteName = keyof typeof routes;

/**
 * Symfony-style path generator for SvelteKit
 */
export function path(name: RouteName, params: Record<string, string | number> = {}): string {
    let url = routes[name] as string;
    if (!url) throw new Error(\`Route "\${name}" not found\`);

    Object.entries(params).forEach(([key, value]) => {
        url = url.replace(\`[\${key}]\`, String(value)).replace(\`[...\${key}]\`, String(value));
    });

    return url.startsWith('/') ? url : '/' + url;
}
`.trim();

    const dir = path.dirname(outputFile);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(outputFile, content);
  };

  return {
    name: "vite-plugin-svelte-named-routes",
    async buildStart() {
      await sync();
    },
    async handleHotUpdate({ file }) {
      if (file.includes("+page.")) {
        await sync();
      }
    },
  };
}
